version: "3.7"

services:
    imgbackremove:
        build: .
        cap_add:
         - ALL
        restart: always
        container_name: "imgbackremove"
        hostname: imgbackremove
        volumes:
         - ./temp:/temp
         - ./web:/web
        dns:
         - 8.8.8.8
         - 8.8.4.4
        ports:
         - "5000:5000"
        deploy:
            resources:
                limits:
                    memory: 150M